### ISSUE TITLE
appwrite configuration missing

### ISSUE THREAD

**Issue by muzammilsyed** [vamshi1107/Mirror#1]
appwrite cloud configuration are missing like collection name, attributes etc,.

**Comment by vamshi1107** [comment]
Collection id and storage id are stored in params.js

**Comment by muzammilsyed** [comment]
Okay. But am taking about appwrite.io end for cloud or self-hosted configs

**Comment by vamshi1107** [comment]
Hi, i am using appwrite cloud for this project
